/**
 * Professional PDF Export Utility
 * Generates properly formatted multi-page PDFs for workout and nutrition plans
 * using jsPDF (no html2canvas — pure text/vector)
 */
import jsPDF from 'jspdf';

// ─── Colour palette ────────────────────────────────────────────────────────
const COLORS = {
  bg:           [10,  12,  26],   // #0a0c1a dark bg
  accent:       [124, 58,  237],  // violet-600
  accentLight:  [167, 139, 250],  // violet-400
  emerald:      [16,  185, 129],  // emerald-500
  amber:        [245, 158, 11],   // amber-500
  white:        [255, 255, 255],
  lightGrey:    [200, 200, 210],
  midGrey:      [130, 130, 150],
  darkGrey:     [50,  50,  65],
  cardBg:       [20,  24,  44],
};

// ─── Helpers ───────────────────────────────────────────────────────────────

function setFill(doc, color) { doc.setFillColor(...color); }
function setDraw(doc, color) { doc.setDrawColor(...color); }
function setTextColor(doc, color) { doc.setTextColor(...color); }

function drawCoverPage(doc, title, subtitle, profile) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // Background
  setFill(doc, COLORS.bg);
  doc.rect(0, 0, W, H, 'F');

  // Accent bar
  setFill(doc, COLORS.accent);
  doc.rect(0, 0, 8, H, 'F');

  // Logo text
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setTextColor(doc, COLORS.accentLight);
  doc.text('PT AI HELPER', 20, 20);

  // Title
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  setTextColor(doc, COLORS.white);
  doc.text(title, 20, H / 2 - 20);

  // Subtitle
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  setTextColor(doc, COLORS.lightGrey);
  doc.text(subtitle, 20, H / 2 + 2);

  // Profile info
  if (profile) {
    const info = [
      `Name: ${profile.name || 'Athlete'}`,
      `Goal: ${profile.goal || '—'}`,
      `Generated: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`,
    ];
    doc.setFontSize(10);
    setTextColor(doc, COLORS.midGrey);
    info.forEach((line, i) => doc.text(line, 20, H / 2 + 22 + i * 8));
  }

  // Footer accent line
  setDraw(doc, COLORS.accent);
  doc.setLineWidth(0.5);
  doc.line(20, H - 20, W - 20, H - 20);

  doc.setFontSize(8);
  setTextColor(doc, COLORS.midGrey);
  doc.text('Powered by Google Gemini AI & USDA FoodData Central', 20, H - 12);
}

function addPageHeader(doc, pageTitle, pageNum) {
  const W = doc.internal.pageSize.getWidth();

  setFill(doc, COLORS.bg);
  doc.rect(0, 0, W, 16, 'F');

  setFill(doc, COLORS.accent);
  doc.rect(0, 0, W, 1.5, 'F');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  setTextColor(doc, COLORS.accentLight);
  doc.text('PT AI HELPER', 10, 10);

  setTextColor(doc, COLORS.midGrey);
  doc.setFont('helvetica', 'normal');
  doc.text(pageTitle, W / 2, 10, { align: 'center' });
  doc.text(`Page ${pageNum}`, W - 10, 10, { align: 'right' });
}

function addPageFooter(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  setDraw(doc, COLORS.darkGrey);
  doc.setLineWidth(0.3);
  doc.line(10, H - 12, W - 10, H - 12);

  doc.setFontSize(7);
  setTextColor(doc, COLORS.midGrey);
  doc.text('This plan is generated by AI. Always consult a qualified professional before starting any new exercise or diet programme.', W / 2, H - 6, { align: 'center' });
}

function checkPageBreak(doc, y, threshold = 265) {
  if (y > threshold) {
    doc.addPage();
    addPageBackground(doc);
    return 25;
  }
  return y;
}

function addPageBackground(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  setFill(doc, COLORS.bg);
  doc.rect(0, 0, W, H, 'F');
}

function formatTimedSteps(steps, fallback) {
  if (!Array.isArray(steps) || steps.length === 0) return fallback || '';
  return steps
    .map((step, idx) => {
      const label = step.name || step.exercise || '';
      const detail = [step.duration, step.reps].filter(Boolean).join(' / ');
      return `${idx + 1}. ${label}${detail ? ` - ${detail}` : ''}`;
    })
    .join('\n');
}

// ─── WORKOUT PDF ──────────────────────────────────────────────────────────

export function downloadWorkoutPDF(plan, profile) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let pageNum = 1;

  // Cover
  drawCoverPage(doc, 'Workout Plan', `Week ${plan.weekNumber || 1} · ${plan.workoutPlan?.focus || ''}`, profile);
  addPageFooter(doc);

  const days = plan.workoutPlan?.days || [];

  days.forEach((day) => {
    doc.addPage();
    addPageBackground(doc);
    pageNum++;
    addPageHeader(doc, 'WEEKLY WORKOUT PLAN', pageNum);
    addPageFooter(doc);

    let y = 24;

    // Day header pill
    setFill(doc, day.isRestDay ? COLORS.darkGrey : COLORS.accent);
    doc.roundedRect(10, y, W - 20, 14, 3, 3, 'F');

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    setTextColor(doc, COLORS.white);
    doc.text(day.dayName || `Day ${day.dayNumber}`, 16, y + 9);

    if (!day.isRestDay) {
      setTextColor(doc, COLORS.accentLight);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(day.focus || '', W - 16, y + 9, { align: 'right' });
    }

    y += 20;

    if (day.isRestDay) {
      setTextColor(doc, COLORS.lightGrey);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text('Active Recovery Day — light stretching, hydration, and mobility work.', 16, y);
      return;
    }

    // Warm-up / Cool-down
    if (day.warmup || day.cooldown || day.warmupSteps || day.cooldownSteps) {
      const warmupText = formatTimedSteps(day.warmupSteps, day.warmup);
      const cooldownText = formatTimedSteps(day.cooldownSteps, day.cooldown);
      const cardH = 36;

      setFill(doc, COLORS.cardBg);
      doc.roundedRect(10, y, (W - 25) / 2, cardH, 2, 2, 'F');
      doc.roundedRect(17 + (W - 25) / 2, y, (W - 25) / 2, cardH, 2, 2, 'F');

      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      setTextColor(doc, COLORS.accentLight);
      doc.text('WARM-UP', 14, y + 6);
      doc.text('COOL-DOWN', 21 + (W - 25) / 2, y + 6);

      doc.setFont('helvetica', 'normal');
      setTextColor(doc, COLORS.lightGrey);
      doc.setFontSize(7);
      const wuLines = doc.splitTextToSize(warmupText, (W - 25) / 2 - 8);
      const cdLines = doc.splitTextToSize(cooldownText, (W - 25) / 2 - 8);
      doc.text(wuLines.slice(0, 7), 14, y + 12);
      doc.text(cdLines.slice(0, 7), 21 + (W - 25) / 2, y + 12);

      y += cardH + 6;
    }

    // Exercise table header
    setFill(doc, COLORS.darkGrey);
    doc.rect(10, y, W - 20, 8, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    setTextColor(doc, COLORS.accentLight);

    const cols = { ex: 12, sets: 90, reps: 108, rest: 125, notes: 143 };
    doc.text('EXERCISE', cols.ex, y + 5.5);
    doc.text('SETS', cols.sets, y + 5.5);
    doc.text('REPS', cols.reps, y + 5.5);
    doc.text('REST', cols.rest, y + 5.5);
    doc.text('COACHING CUES', cols.notes, y + 5.5);
    y += 9;

    (day.exercises || []).forEach((ex, idx) => {
      y = checkPageBreak(doc, y);

      const rowH = 12;
      setFill(doc, idx % 2 === 0 ? COLORS.cardBg : COLORS.bg);
      doc.rect(10, y, W - 20, rowH, 'F');

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      setTextColor(doc, COLORS.white);
      doc.text(String(ex.name || ''), cols.ex, y + 7.5);

      doc.setFont('helvetica', 'normal');
      setTextColor(doc, COLORS.lightGrey);
      doc.text(String(ex.sets || ''), cols.sets, y + 7.5);
      doc.text(String(ex.reps || ''), cols.reps, y + 7.5);
      doc.text(String(ex.rest || ''), cols.rest, y + 7.5);

      const noteLines = doc.splitTextToSize(String(ex.notes || ''), 55);
      doc.setFontSize(7);
      setTextColor(doc, COLORS.midGrey);
      doc.text(noteLines.slice(0, 2), cols.notes, y + 5);

      y += rowH;
    });

    // Progressive overload note if present
    if (day.progressiveOverload) {
      y = checkPageBreak(doc, y + 4);
      setFill(doc, [30, 20, 60]);
      doc.roundedRect(10, y, W - 20, 14, 2, 2, 'F');
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      setTextColor(doc, COLORS.accentLight);
      doc.text('📈 PROGRESSIVE OVERLOAD THIS WEEK:', 14, y + 5);
      doc.setFont('helvetica', 'normal');
      setTextColor(doc, COLORS.lightGrey);
      const poLines = doc.splitTextToSize(day.progressiveOverload, W - 40);
      doc.text(poLines.slice(0, 2), 14, y + 11);
      y += 18;
    }
  });

  doc.save(`PT_AI_Workout_Week${plan.weekNumber || 1}_${(profile?.name || 'Plan').replace(/\s+/g, '_')}.pdf`);
}

// ─── NUTRITION PDF ────────────────────────────────────────────────────────

export function downloadNutritionPDF(plan, profile) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let pageNum = 1;

  // Cover
  drawCoverPage(
    doc,
    'Nutrition Plan',
    `Week ${plan.weekNumber || 1} · ${plan.nutritionPlan?.focus || ''}`,
    profile
  );
  addPageFooter(doc);

  const nutritionPlan = plan.nutritionPlan || {};
  const mealDays = plan.weeklyMealPlan || null;

  // ── Daily targets summary page ──
  doc.addPage();
  addPageBackground(doc);
  pageNum++;
  addPageHeader(doc, 'DAILY NUTRITIONAL TARGETS', pageNum);
  addPageFooter(doc);

  let y = 28;

  // Big calorie box
  setFill(doc, COLORS.accent);
  doc.roundedRect(10, y, W - 20, 28, 4, 4, 'F');
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  setTextColor(doc, COLORS.white);
  doc.text(`${nutritionPlan.dailyTargetCalories || '—'} kcal/day`, W / 2, y + 16, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setTextColor(doc, COLORS.accentLight);
  doc.text('TARGET DAILY CALORIC INTAKE', W / 2, y + 24, { align: 'center' });
  y += 36;

  // Macro boxes
  const macroBoxW = (W - 40) / 3;
  const macroData = [
    { label: 'PROTEIN', value: `${nutritionPlan.dailyMacros?.protein || '—'}g`, color: COLORS.accentLight },
    { label: 'CARBS',   value: `${nutritionPlan.dailyMacros?.carbs   || '—'}g`, color: COLORS.emerald },
    { label: 'FATS',    value: `${nutritionPlan.dailyMacros?.fat     || '—'}g`, color: COLORS.amber },
  ];

  macroData.forEach((m, i) => {
    const x = 10 + i * (macroBoxW + 5);
    setFill(doc, COLORS.cardBg);
    doc.roundedRect(x, y, macroBoxW, 22, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    setTextColor(doc, m.color);
    doc.text(m.label, x + macroBoxW / 2, y + 7, { align: 'center' });
    doc.setFontSize(16);
    setTextColor(doc, COLORS.white);
    doc.text(m.value, x + macroBoxW / 2, y + 17, { align: 'center' });
  });

  y += 30;

  // General advice
  if (nutritionPlan.generalAdvice) {
    setFill(doc, COLORS.cardBg);
    const adviceLines = doc.splitTextToSize(nutritionPlan.generalAdvice, W - 36);
    const boxH = adviceLines.length * 5 + 14;
    doc.roundedRect(10, y, W - 20, boxH, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    setTextColor(doc, COLORS.emerald);
    doc.text('COACHING NOTES', 16, y + 8);
    doc.setFont('helvetica', 'normal');
    setTextColor(doc, COLORS.lightGrey);
    doc.setFontSize(8);
    doc.text(adviceLines, 16, y + 14);
    y += boxH + 8;
  }

  // ── Meal plan pages ──
  const days = mealDays || [{ dayName: 'Daily Meals', meals: nutritionPlan.meals || [] }];

  days.forEach((day) => {
    doc.addPage();
    addPageBackground(doc);
    pageNum++;
    addPageHeader(doc, 'WEEKLY NUTRITION PLAN', pageNum);
    addPageFooter(doc);

    let y = 24;

    // Day header
    setFill(doc, COLORS.emerald);
    doc.roundedRect(10, y, W - 20, 12, 3, 3, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    setTextColor(doc, COLORS.bg);
    doc.text(day.dayName || 'Meals', 16, y + 8.5);
    y += 18;

    (day.meals || []).forEach((meal) => {
      y = checkPageBreak(doc, y, 260);

      // Meal header
      setFill(doc, COLORS.cardBg);
      doc.roundedRect(10, y, W - 20, 12, 2, 2, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      setTextColor(doc, COLORS.white);
      doc.text(meal.name || 'Meal', 14, y + 8);

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      setTextColor(doc, COLORS.midGrey);
      doc.text(meal.time || '', W - 14, y + 8, { align: 'right' });
      y += 14;

      // Ingredients
      (meal.enrichedIngredients || meal.ingredients || []).forEach((ing, idx) => {
        y = checkPageBreak(doc, y, 260);

        const isEnriched = typeof ing === 'object';
        const ingText = isEnriched ? ing.ingredient : ing;
        const usdaLine = isEnriched && ing.source === 'usda'
          ? `  ${ing.calories}kcal · P${ing.protein}g · C${ing.carbs}g · F${ing.fat}g · Fibre${ing.fibre}g`
          : '';

        setFill(doc, idx % 2 === 0 ? [16, 20, 38] : COLORS.bg);
        const rowH = isEnriched && ing.source === 'usda' ? 14 : 8;
        doc.rect(14, y, W - 28, rowH, 'F');

        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        setTextColor(doc, COLORS.lightGrey);
        doc.text(`• ${ingText}`, 16, y + 5.5);

        if (usdaLine) {
          doc.setFontSize(6.5);
          setTextColor(doc, COLORS.emerald);
          doc.text(usdaLine, 20, y + 11);
        }

        y += rowH;
      });

      // Meal totals strip
      const cal  = meal.usdaCalories  ?? meal.calories;
      const prot = meal.usdaProtein   ?? meal.macros?.protein;
      const carb = meal.usdaCarbs     ?? meal.macros?.carbs;
      const fat  = meal.usdaFat       ?? meal.macros?.fat;
      const fib  = meal.usdaFibre;
      const src  = meal.dataSource === 'usda' ? 'USDA verified' : 'AI estimate';

      setFill(doc, COLORS.darkGrey);
      doc.roundedRect(14, y + 2, W - 28, 12, 2, 2, 'F');

      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      setTextColor(doc, COLORS.white);
      doc.text(`${cal ?? '—'} kcal`, 18, y + 9.5);

      doc.setFont('helvetica', 'normal');
      setTextColor(doc, COLORS.lightGrey);
      const macroStr = [
        prot != null ? `P: ${prot}g` : '',
        carb != null ? `C: ${carb}g` : '',
        fat  != null ? `F: ${fat}g`  : '',
        fib  != null ? `Fibre: ${fib}g` : '',
      ].filter(Boolean).join('  ·  ');
      doc.text(macroStr, 18 + 22, y + 9.5);

      doc.setFontSize(6.5);
      setTextColor(doc, meal.dataSource === 'usda' ? COLORS.emerald : COLORS.midGrey);
      doc.text(src, W - 14, y + 9.5, { align: 'right' });

      y += 20;
    });
  });

  doc.save(`PT_AI_Nutrition_Week${plan.weekNumber || 1}_${(profile?.name || 'Plan').replace(/\s+/g, '_')}.pdf`);
}
