import jsPDF from 'jspdf';

// ─── Theme → PDF colors ────────────────────────────────────────────────────
const THEME_PALETTES = {
  slate:    { bg: [2,  6,  23],  card: [12, 16, 40],  row: [16, 20, 48] },
  navy:     { bg: [2,  12, 36],  card: [8,  20, 52],  row: [12, 26, 62] },
  purple:   { bg: [12, 5,  32],  card: [22, 12, 48],  row: [28, 16, 56] },
  forest:   { bg: [2,  20, 9],   card: [6,  30, 16],  row: [10, 36, 20] },
  charcoal: { bg: [8,  8,  8],   card: [18, 18, 20],  row: [24, 24, 26] },
  wine:     { bg: [21, 4,  8],   card: [32, 8,  14],  row: [38, 12, 18] },
};

function getThemePalette() {
  const id = localStorage.getItem('dbsai_bg_theme') || 'slate';
  return THEME_PALETTES[id] || THEME_PALETTES.slate;
}

// ─── Shared colors ─────────────────────────────────────────────────────────
const C = {
  accent:      [124, 58,  237],
  accentLight: [167, 139, 250],
  emerald:     [16,  185, 129],
  amber:       [245, 158, 11],
  white:       [255, 255, 255],
  lightGrey:   [200, 200, 210],
  midGrey:     [130, 130, 150],
  darkGrey:    [50,  50,  65],
};

// ─── Helpers ───────────────────────────────────────────────────────────────
const sf  = (doc, col) => doc.setFillColor(...col);
const sd  = (doc, col) => doc.setDrawColor(...col);
const stc = (doc, col) => doc.setTextColor(...col);

function drawPageBackground(doc, palette) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  sf(doc, palette.bg);
  doc.rect(0, 0, W, H, 'F');
}

function addPageHeader(doc, centerText, pageNum, palette) {
  const W = doc.internal.pageSize.getWidth();
  sf(doc, palette.bg);
  doc.rect(0, 0, W, 16, 'F');
  sf(doc, C.accent);
  doc.rect(0, 0, W, 1.5, 'F');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  stc(doc, C.accentLight);
  doc.text("DB's AI", 10, 10);

  stc(doc, C.midGrey);
  doc.setFont('helvetica', 'normal');
  doc.text(centerText, W / 2, 10, { align: 'center' });
  doc.text(`Page ${pageNum}`, W - 10, 10, { align: 'right' });
}

function addPageFooter(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  sd(doc, C.darkGrey);
  doc.setLineWidth(0.3);
  doc.line(10, H - 12, W - 10, H - 12);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  stc(doc, C.midGrey);
  doc.text(
    'This plan is generated by AI. Always consult a qualified professional before starting any new exercise or diet programme.',
    W / 2, H - 6, { align: 'center' }
  );
}

function checkPageBreak(doc, y, palette, threshold = 265) {
  if (y > threshold) {
    doc.addPage();
    drawPageBackground(doc, palette);
    return 25;
  }
  return y;
}

function drawCoverPage(doc, title, subtitle, profile, palette) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  drawPageBackground(doc, palette);

  sf(doc, C.accent);
  doc.rect(0, 0, 8, H, 'F');

  // Brand
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  stc(doc, C.accentLight);
  doc.text("DB's AI", 20, 20);

  // Title
  const midY = H / 2 - 30;
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  stc(doc, C.white);
  doc.text(title, 20, midY);

  // Subtitle — wrap so it doesn't overflow
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  stc(doc, C.lightGrey);
  const subLines = doc.splitTextToSize(subtitle, W - 40);
  doc.text(subLines, 20, midY + 14);

  // Profile info
  const infoY = midY + 14 + subLines.length * 7 + 10;
  const info = [
    `Name: ${profile?.name || 'Athlete'}`,
    `Goal: ${profile?.goal || '—'}`,
    `Generated: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}`,
  ];
  doc.setFontSize(10);
  stc(doc, C.midGrey);
  info.forEach((line, i) => doc.text(line, 20, infoY + i * 8));

  // Footer line
  sd(doc, C.accent);
  doc.setLineWidth(0.5);
  doc.line(20, H - 20, W - 20, H - 20);
  doc.setFontSize(8);
  stc(doc, C.midGrey);
  doc.text("Powered by DB's AI · AI-generated personalised training", 20, H - 12);
}

function formatSteps(steps, fallback) {
  if (!Array.isArray(steps) || !steps.length) return fallback || '';
  return steps
    .map((s, i) => {
      const detail = [s.duration, s.reps].filter(Boolean).join(' / ');
      return `${i + 1}. ${s.name || s.exercise || ''}${detail ? ` — ${detail}` : ''}`;
    })
    .join('\n');
}

// ─── WORKOUT PDF ───────────────────────────────────────────────────────────
export function downloadWorkoutPDF(plan, profile) {
  const palette = getThemePalette();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let pageNum = 1;

  drawCoverPage(doc, 'Workout Plan', `Week ${plan.weekNumber || 1} · ${plan.workoutPlan?.focus || '7-Day Training Programme'}`, profile, palette);
  addPageFooter(doc);

  const days = plan.workoutPlan?.days || [];

  // Column positions (A4 = 210mm, margins 10mm each side)
  const COL = { ex: 12, sets: 86, reps: 100, rest: 126, notes: 142 };
  const COL_W = { ex: 72, reps: 24, rest: 14, notes: 56 };

  days.forEach((day) => {
    doc.addPage();
    drawPageBackground(doc, palette);
    pageNum++;
    addPageHeader(doc, 'WEEKLY WORKOUT PLAN', pageNum, palette);
    addPageFooter(doc);

    let y = 24;

    // Day header
    sf(doc, day.isRestDay ? C.darkGrey : C.accent);
    doc.roundedRect(10, y, W - 20, 14, 3, 3, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    stc(doc, C.white);
    doc.text(day.dayName || `Day ${day.dayNumber}`, 16, y + 9.5);
    if (!day.isRestDay && day.focus) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      stc(doc, C.accentLight);
      const focusLines = doc.splitTextToSize(day.focus, W - 80);
      doc.text(focusLines[0], W - 16, y + 9.5, { align: 'right' });
    }
    y += 20;

    if (day.isRestDay) {
      stc(doc, C.lightGrey);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text('Active Recovery Day — light stretching, hydration, and mobility work.', 16, y);
      return;
    }

    // Warm-up / Cool-down cards
    const warmupText = formatSteps(day.warmupSteps, day.warmup);
    const cooldownText = formatSteps(day.cooldownSteps, day.cooldown);
    if (warmupText || cooldownText) {
      const colW = (W - 25) / 2;
      const wuLines = doc.splitTextToSize(warmupText, colW - 8);
      const cdLines = doc.splitTextToSize(cooldownText, colW - 8);
      const cardH = Math.max(wuLines.length, cdLines.length) * 4.5 + 14;

      sf(doc, palette.card);
      doc.roundedRect(10, y, colW, cardH, 2, 2, 'F');
      doc.roundedRect(17 + colW, y, colW, cardH, 2, 2, 'F');

      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      stc(doc, C.accentLight);
      doc.text('WARM-UP', 14, y + 6);
      doc.text('COOL-DOWN', 21 + colW, y + 6);

      doc.setFont('helvetica', 'normal');
      stc(doc, C.lightGrey);
      doc.setFontSize(7);
      doc.text(wuLines, 14, y + 12);
      doc.text(cdLines, 21 + colW, y + 12);
      y += cardH + 6;
    }

    // Table header
    sf(doc, C.darkGrey);
    doc.rect(10, y, W - 20, 8, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    stc(doc, C.accentLight);
    doc.text('EXERCISE',     COL.ex,    y + 5.5);
    doc.text('SETS',         COL.sets,  y + 5.5);
    doc.text('REPS',         COL.reps,  y + 5.5);
    doc.text('REST',         COL.rest,  y + 5.5);
    doc.text('COACHING CUES',COL.notes, y + 5.5);
    y += 9;

    (day.exercises || []).forEach((ex, idx) => {
      // Compute wrapped lines per column first so we know the row height
      doc.setFontSize(8);
      const exLines    = doc.splitTextToSize(String(ex.name  || ''), COL_W.ex);
      const repsLines  = doc.splitTextToSize(String(ex.reps  || ''), COL_W.reps);
      const restLines  = doc.splitTextToSize(String(ex.rest  || ''), COL_W.rest);
      doc.setFontSize(7);
      const noteLines  = doc.splitTextToSize(String(ex.notes || ''), COL_W.notes).slice(0, 4);

      const LINE_H = 4.5;
      const rowH = Math.max(exLines.length, repsLines.length, restLines.length, noteLines.length) * LINE_H + 5;

      y = checkPageBreak(doc, y, palette);

      sf(doc, idx % 2 === 0 ? palette.card : palette.row);
      doc.rect(10, y, W - 20, rowH, 'F');

      // Exercise name
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      stc(doc, C.white);
      doc.text(exLines, COL.ex, y + 4.5);

      // Sets (single value, centred in column)
      doc.setFont('helvetica', 'normal');
      stc(doc, C.lightGrey);
      doc.text(String(ex.sets || ''), COL.sets, y + 4.5);

      // Reps — wrapped
      doc.text(repsLines, COL.reps, y + 4.5);

      // Rest — wrapped
      doc.text(restLines, COL.rest, y + 4.5);

      // Notes
      doc.setFontSize(7);
      stc(doc, C.midGrey);
      doc.text(noteLines, COL.notes, y + 4.5);

      y += rowH;
    });

    // Progressive overload
    if (day.progressiveOverload) {
      y = checkPageBreak(doc, y + 4, palette);
      doc.setFontSize(7);
      const poLines = doc.splitTextToSize(day.progressiveOverload, W - 40);
      const boxH = poLines.length * 4.5 + 14;
      sf(doc, [30, 20, 60]);
      doc.roundedRect(10, y, W - 20, boxH, 2, 2, 'F');
      doc.setFont('helvetica', 'bold');
      stc(doc, C.accentLight);
      doc.text('PROGRESSIVE OVERLOAD THIS WEEK:', 14, y + 6);
      doc.setFont('helvetica', 'normal');
      stc(doc, C.lightGrey);
      doc.text(poLines, 14, y + 12);
      y += boxH + 4;
    }
  });

  const name = (profile?.name || 'Plan').replace(/\s+/g, '_');
  doc.save(`DBs_AI_Workout_Week${plan.weekNumber || 1}_${name}.pdf`);
}

// ─── NUTRITION PDF ─────────────────────────────────────────────────────────
export function downloadNutritionPDF(plan, profile) {
  const palette = getThemePalette();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  let pageNum = 1;

  drawCoverPage(
    doc,
    'Nutrition Plan',
    `Week ${plan.weekNumber || 1} · ${plan.nutritionPlan?.focus || '7-Day Meal Programme'}`,
    profile,
    palette
  );
  addPageFooter(doc);

  const nutritionPlan = plan.nutritionPlan || {};

  // ── Daily targets page ──
  doc.addPage();
  drawPageBackground(doc, palette);
  pageNum++;
  addPageHeader(doc, 'DAILY NUTRITIONAL TARGETS', pageNum, palette);
  addPageFooter(doc);

  let y = 28;

  sf(doc, C.accent);
  doc.roundedRect(10, y, W - 20, 28, 4, 4, 'F');
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  stc(doc, C.white);
  doc.text(`${nutritionPlan.dailyTargetCalories || '—'} kcal/day`, W / 2, y + 16, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  stc(doc, C.accentLight);
  doc.text('TARGET DAILY CALORIC INTAKE', W / 2, y + 24, { align: 'center' });
  y += 36;

  const macroBoxW = (W - 40) / 3;
  [
    { label: 'PROTEIN', value: `${nutritionPlan.dailyMacros?.protein || '—'}g`, color: C.accentLight },
    { label: 'CARBS',   value: `${nutritionPlan.dailyMacros?.carbs   || '—'}g`, color: C.emerald },
    { label: 'FATS',    value: `${nutritionPlan.dailyMacros?.fat     || '—'}g`, color: C.amber },
  ].forEach((m, i) => {
    const x = 10 + i * (macroBoxW + 5);
    sf(doc, palette.card);
    doc.roundedRect(x, y, macroBoxW, 22, 3, 3, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    stc(doc, m.color);
    doc.text(m.label, x + macroBoxW / 2, y + 7, { align: 'center' });
    doc.setFontSize(16);
    stc(doc, C.white);
    doc.text(m.value, x + macroBoxW / 2, y + 17, { align: 'center' });
  });
  y += 30;

  if (nutritionPlan.generalAdvice) {
    doc.setFontSize(8);
    const advLines = doc.splitTextToSize(nutritionPlan.generalAdvice, W - 36);
    const boxH = advLines.length * 5 + 14;
    sf(doc, palette.card);
    doc.roundedRect(10, y, W - 20, boxH, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    stc(doc, C.emerald);
    doc.text('COACHING NOTES', 16, y + 8);
    doc.setFont('helvetica', 'normal');
    stc(doc, C.lightGrey);
    doc.text(advLines, 16, y + 14);
    y += boxH + 8;
  }

  // ── Meal pages ──
  const days = plan.weeklyMealPlan || [{ dayName: 'Daily Meals', meals: nutritionPlan.meals || [] }];

  days.forEach((day) => {
    doc.addPage();
    drawPageBackground(doc, palette);
    pageNum++;
    addPageHeader(doc, 'WEEKLY NUTRITION PLAN', pageNum, palette);
    addPageFooter(doc);

    let y = 24;

    sf(doc, C.emerald);
    doc.roundedRect(10, y, W - 20, 12, 3, 3, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    stc(doc, palette.bg);
    doc.text(day.dayName || 'Meals', 16, y + 8.5);
    y += 18;

    (day.meals || []).forEach((meal) => {
      y = checkPageBreak(doc, y, palette, 260);

      // Meal header
      sf(doc, palette.card);
      doc.roundedRect(10, y, W - 20, 12, 2, 2, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      stc(doc, C.white);
      doc.text(meal.name || 'Meal', 14, y + 8);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      stc(doc, C.midGrey);
      doc.text(meal.time || '', W - 14, y + 8, { align: 'right' });
      y += 14;

      // Ingredients
      (meal.enrichedIngredients || meal.ingredients || []).forEach((ing, i) => {
        y = checkPageBreak(doc, y, palette, 260);

        const isEnriched = typeof ing === 'object' && ing !== null;
        const label = isEnriched ? (ing.ingredient || ing.name || '') : (typeof ing === 'string' ? ing : '');
        const hasUsda = isEnriched && ing.source === 'usda';
        const rowH = hasUsda ? 13 : 8;

        sf(doc, i % 2 === 0 ? palette.card : palette.row);
        doc.rect(14, y, W - 28, rowH, 'F');

        const ingLines = doc.splitTextToSize(`• ${label}`, W - 36);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        stc(doc, C.lightGrey);
        doc.text(ingLines[0], 16, y + 5.5);

        if (hasUsda) {
          doc.setFontSize(6.5);
          stc(doc, C.emerald);
          doc.text(`  ${ing.calories ?? ''}kcal · P${ing.protein ?? ''}g · C${ing.carbs ?? ''}g · F${ing.fat ?? ''}g`, 20, y + 10.5);
        }

        y += rowH;
      });

      // Meal totals
      const cal  = meal.usdaCalories ?? meal.calories;
      const prot = meal.usdaProtein  ?? meal.macros?.protein;
      const carb = meal.usdaCarbs    ?? meal.macros?.carbs;
      const fat  = meal.usdaFat      ?? meal.macros?.fat;
      const fib  = meal.usdaFibre;

      sf(doc, C.darkGrey);
      doc.roundedRect(14, y + 2, W - 28, 11, 2, 2, 'F');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      stc(doc, C.white);
      doc.text(`${cal ?? '—'} kcal`, 18, y + 8.5);

      doc.setFont('helvetica', 'normal');
      stc(doc, C.lightGrey);
      const macroStr = [
        prot != null ? `P: ${prot}g` : '',
        carb != null ? `C: ${carb}g` : '',
        fat  != null ? `F: ${fat}g`  : '',
        fib  != null ? `Fibre: ${fib}g` : '',
      ].filter(Boolean).join('  ·  ');
      doc.text(macroStr, 42, y + 8.5);

      doc.setFontSize(6.5);
      stc(doc, meal.dataSource === 'usda' ? C.emerald : C.midGrey);
      doc.text(meal.dataSource === 'usda' ? 'USDA verified' : 'AI estimate', W - 14, y + 8.5, { align: 'right' });

      y += 18;
    });
  });

  const name = (profile?.name || 'Plan').replace(/\s+/g, '_');
  doc.save(`DBs_AI_Nutrition_Week${plan.weekNumber || 1}_${name}.pdf`);
}
